<a href="https://colab.research.google.com/github/Naveen1234321/Machine-Learning-/blob/main/LAB1_Numpy_11502.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
arr=np.array([0,1,2])
print(type(arr))
print(arr.shape)
print(arr[0])
print(arr[1])                   #  rank is dimension
print(arr[2])
arr[0]=10
print(arr)

arr2=np.array([[1,2,3],[4,5,6]])
print(type(arr2))
print(arr2.shape)
zeroes=np.zeros((3,3))
print(zeroes)

fulls=np.full((4,4),10)
print(fulls)

rand=np.random.random((3,3))
print(rand)

e=np.eye(3)                               #eye gives diagonal matrix
print(e)


# Convert list to NumPy array
f = np.array([2, 3, 1, 0])
print(f)

# 1D array with values 0 to 19
g = np.arange(20)
print(g)

# Mix of types (int, float, complex)
h = np.array([[0, 1, 2.0], [0, 0, 0], (1+1j, 3., 2.)])
print(h)

# Range with float data type
i = np.arange(1, 8, dtype=np.float64)
print(i)

# Linspace: 5 values equally spaced between 2 and 4
j = np.linspace(2, 4, 5)
print(j)



# Example 3: NumPy Data Types


# Auto dtype
x = np.array([0, 1])
y = np.array([2.0, 3.0])

# Explicit dtype
z = np.array([5, 6], dtype=np.int64)

# Print dtypes
print(x.dtype, y.dtype, z.dtype)



# Example 4: Indexing and Slicing

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Slicing: first 2 rows, alternate columns (0 and 2)
temp = arr[:2, ::2]
print("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

# Integer array indexing
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print("Elements at indices (0,3), (1,2), (2,1), (3,0):\n", temp)

# Boolean indexing: elements > 0
cond = arr > 0
temp = arr[cond]
print("Elements greater than 0:\n", temp)



# Example 5: Basic Array Operations

a = np.array([1, 2, 5, 3])

print("Adding 1 to every element:", a + 1)
print("Subtracting 3 from each element:", a - 3)
print("Multiplying each element by 10:", a * 10)
print("Squaring each element:", a ** 2)

# Modify array in-place (double elements)
a *= 2
print("Doubled each element of original array:", a)

# Transpose of a 2D array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print("Original array:\n", a)
print("Transpose of array:\n", a.T)



# Example 6: Unary Operators

arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])

# Max value
print("Largest element is:", arr.max())

# Row-wise max
print("Row-wise maximum elements:", arr.max(axis=1))

# Column-wise min
print("Column-wise minimum elements:", arr.min(axis=0))

# Sum of all elements
print("Sum of all array elements:", arr.sum())

# Cumulative sum along each row
print("Cumulative sum along each row:\n", arr.cumsum(axis=1))



# Example 7: Binary Operators

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[4, 3],
              [2, 1]])

# Element-wise addition
print("Array sum:\n", a + b)

# Element-wise multiplication
print("Array multiplication:\n", a * b)

# Matrix multiplication
print("Matrix multiplication:\n", a.dot(b))



# Example 8: Universal Functions (ufunc)

# Sine of elements
a = np.array([0, np.pi/2, np.pi])
print("Sine values of array elements:", np.sin(a))

# Exponential values
a = np.array([0, 1, 2, 3])
print("Exponent of array elements:", np.exp(a))

# Square root
print("Square root of array elements:", np.sqrt(a))



# Example 9: Matrix Inverse

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Inverse of 4x4 matrix
inverse = np.linalg.inv(arr)
print(inverse)

<class 'numpy.ndarray'>
(3,)
0
1
2
[10  1  2]
<class 'numpy.ndarray'>
(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0.17302782 0.72103684 0.73863095]
 [0.505839   0.12007996 0.560442  ]
 [0.50184685 0.55376093 0.87256437]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 3 1 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]
[1. 2. 3. 4. 5. 6. 7.]
[2.  2.5 3.  3.5 4. ]
int64 float64 int64
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]
Elements at indices (0,3), (1,2), (2,1), (3,0):
 [4. 6. 0. 3.]
Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]
Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]
Original array:
 [[1 2 3]
 [3 4 5]
 [